config/routes.rb
Rails.application.routes.draw do
  resources :daily_updates
  devise_for :users , controllers: { sessions: "sessions" }
  root 'daily_updates#index'
  namespace :admin do
    resources :manage_user
    resources :users
    resources :categories
    get 'deactivate' => 'manage_user#deactivate', :as=>'deactivate'
    get 'daily_updates/index'
  end
    get 'past_clients'=>"admin/daily_updates#past_clients"
    get 'check_msg'=>"daily_updates#check_msg"
    get 'add_contracts'=>'admin/daily_updates#index_contract'
    get 'new_contract' => 'admin/daily_updates#new_contract'
    get 'scheduled_call' => 'daily_updates#scheduled_call'
    post 'create_contract' => 'admin/daily_updates#create_contract'
    get 'fetch_plans' => 'admin/daily_updates#fetch_plans'
    get 'fetch_meetings' => 'admin/daily_updates#fetch_meetings'
    get 'fetch_logs' => 'admin/daily_updates#logs'
    get 'fetch_contract' => 'admin/daily_updates#fetch_contract'
    get 'fetch_daily' => 'daily_updates#fetch_daily'
    get 'index_contract' => 'admin/daily_updates#index_contract'
    get 'edit_contract' => 'admin/daily_updates#edit_contract'
    post 'update_contract' => 'admin/daily_updates#update_contract'
    post 'call' => 'daily_updates#call'
    post 'call_meeting' => 'daily_updates#call_meeting'
    get 'show_meetings' => 'admin/daily_updates#show_meetings'
    get 'lead_statuses' => 'daily_updates#scheduled_call'
    get 'meeting_logs' => 'daily_updates#meeting_logs'
    get 'not_called'=>'admin/daily_updates#not_called'
    get 'contract_updates'=>'daily_updates#contract_updates'
    get 'messages'=>'daily_updates#messages'
    get 'view_more'=>'daily_updates#view_more'
    get 'new_message'=>'daily_updates#new_message'
    post 'new_message'=>'daily_updates#new_message'
    post 'contract_updates'=>'daily_updates#contract_updates'
    get 'client_meetings'=>'daily_updates#client_meetings'
    get 'todays_meetings'=>'daily_updates#todays_meetings'
  as :admin do
    post 'notify_expiry'=>'admin/daily_updates#notify_expiry'
    post 'lead_statuses'=>'admin/daily_updates#daily_report'
    get 'daily_report'=>'admin/daily_updates#daily_report'
    post 'admin/new_users' => 'admin/users#create'
    post 'user_daily_updates' => 'admin/daily_updates#user_daily_updates'
    post 'schedule_meeting'=>'daily_updates#schedule_meeting'
    post 'schedule_meetings'=>'admin/daily_updates#meetings'
    get 'schedule_meetings'=>'admin/daily_updates#meetings'
    get 'payment_histories'=>'admin/daily_updates#reports'
    post 'reports'=>'admin/daily_updates#reports'
    get 'user_daily_updates' => 'admin/daily_updates#user_daily_updates'
    get 'meetings'=>'admin/daily_updates#meetings'
    get 'edit_meetings'=>'admin/daily_updates#edit_meetings'
    post 'update_meetings'=>'admin/daily_updates#update_meetings'
    get 'client_management' => 'admin/daily_updates#client_management'
    get 'payment_history' => 'admin/daily_updates#payment_history'
    get 'contract_expiry' => 'admin/daily_updates#contract_expiry'
    post 'contract_expiry' => 'admin/daily_updates#contract_expiry'
    post 'create_payment' => 'admin/daily_updates#create_payment'    
  end
end

app/controllers/admin/daily_updates_controller.rb
class Admin::DailyUpdatesController < ApplicationController
  before_filter :check_user, :only => [:index,:user_daily_updates]
  respond_to :html
  
  def check_user
  	redirect_to daily_updates_path if current_user.role !="Admin" or !current_user.admin?
  end

  def index    
    @user=User.all
    @category=Category.all
    @search = DailyUpdate.search(params[:q])
    if params[:q].nil?
       @daily_updates = @search.result.where(:status=>"0").order('created_at DESC').page(params[:page]).per(25)
    else
      @daily_updates = @search.result.order('created_at DESC').page(params[:page]).per(25)
    end
    respond_with(@daily_updates)
  end
  
  def user_daily_updates
  	@daily_updates=User.find(params[:id]).daily_updates.order("created_at").page(params[:page]).per(25)
  end
  
  def fetch_meetings
    @meetings=ScheduleMeeting.find(params[:meeting_id])
    render :json =>@meetings
  end

  def notify_expiry
    @user=DailyUpdate.find(params[:id])
    NotificationMailer.expiry_notification(@user,params[:contract_id]).deliver
    redirect_to :back
  end
  
  def meetings
    @m=[]
    @user=User.all
    @meetings=[]
    @search = DailyUpdate.search(params[:q])
    @search.result.each do |daily|
      if daily.schedule_meeting.present?
        if @meetings.include?(daily.schedule_meeting.last.id )
        else
          @meetings<<daily.schedule_meeting.last.id
        end
        daily.schedule_meeting.each do |sm|
          if sm.meeting_date.present?
            if sm.mom==nil and sm.meeting_date<Date.today 
              if @m.include?(sm )
              else
                @m<<sm
              end
            end
          end
        end
      end
    end
  end
  
  def edit_meetings
    @user=User.all
    @meeting=ScheduleMeeting.find(params[:id])
  end

  def update_meetings
    if params[:commit]=="Save Only Mom"
      @meeting=ScheduleMeeting.find(params[:ss_id])
      @meeting.update(:mom=>params[:mom])
    elsif params[:commit]=="Submit"
	    @meeting=ScheduleMeeting.find(params[:s_id])
      @meeting.update(:meeting_date=>params[:meeting_date],:meeting_time=>params[:meeting_time],:venue=>params[:venue],:notes=>params[:notes]) 
    else
      @meeting=ScheduleMeeting.find(params[:ss_id])
      @meeting.update(:mom=>params[:mom])
      meeting_no= ScheduleMeeting.connection.execute("SELECT nextval('meeting_num_seq')")
      meeting='SE'+'0'+meeting_no[0]['nextval']
      @schedule=ScheduleMeeting.new(:meeting_no=>meeting,:meeting_date=>params[:meeting_date],:notes=>params[:notes],:assigned_to=>params[:assigned_to],:meeting_time=>params[:meeting_time],:venue=>params[:venue],:daily_update_id=>params[:daily_update_id])
      @schedule.save
    end
    redirect_to :back
  end

  def client_management
    @user=User.all
    @search = DailyUpdate.search(params[:q])
    @daily_updates = @search.result
    respond_with(@daily_updates)
  end

  def new_contract
    @add_contract=AddContract.new
    @client=DailyUpdate.includes(:lead_status).where('lead_statuses.state =?', 'Client').references(:lead_status)
  end

  def show_meetings
    @meeting=ScheduleMeeting.find(params[:id])
  end

  def create_contract
    @add_contract=AddContract.create(:priority=>params[:priority],:daily_update_id=>params[:client_id],:status=>params[:status],:domain_name=>params[:domain_name],:work_status=>params[:work_status])
    @plan=Plan.create(:plan_type=>params[:plan],:renewal_date=>params[:renewal_date],:add_contract_id=>@add_contract.id)
    redirect_to :back
  end

  def fetch_plans
    if params[:plans]=="1 month"
      @renewal_date=  Time.now + 1.month
    elsif params[:plans]=="2 month"
      @renewal_date=  Time.now + 2.month
    elsif params[:plans]=="quaterly"
      @renewal_date=  Time.now + 3.month
    elsif params[:plans]=="half yearly"
      @renewal_date=  Time.now + 6.month
    else params[:plans]=="yearly"
      @renewal_date=  Time.now + 12.month
    end
   render :json =>@renewal_date
  end

  def index_contract
    @client=DailyUpdate.includes(:lead_status).where('lead_statuses.state =?', 'Client').references(:lead_status)
    @search = AddContract.search(params[:q])
    @contracts=@search.result
    respond_with(@contracts)
  end

  def edit_contract
    @contract=AddContract.find(params[:contract_id])
    @plans=Plan.where(:add_contract_id=>params[:id])
    @client=DailyUpdate.includes(:lead_status).where('lead_statuses.state =?', 'Client').references(:lead_status)
  end

  def fetch_contract
    @contract=AddContract.find(params[:contract])
    @plan=Plan.where(:add_contract_id=>@contract).last
    render :json => {:contract => @contract, :plan => @plan }
  end
  
  def update_contract
    @contract=AddContract.find(params[:contract_id])
    @contract.update(:priority=>params[:priority],:daily_update_id=>params[:client_id],:work_status=>params[:work_status],:status=>params[:status],:domain_name=>params[:domain_name])
    @plan=Plan.create(:plan_type=>params[:plan],:renewal_date=>params[:renewal_date],:add_contract_id=>params[:contract_id])
    redirect_to :index_contract
  end

  def payment_history
    @payment_history=PaymentHistory.where(:add_contract_id=>params[:id]).order("created_at DESC")
  end

  def create_payment
    @payment=PaymentHistory.create(:collection_date=>params[:collection_date],:amount=>params[:amount],:cheque_no=>params[:cheque_no],:bank_name=>params[:bank_name],:cheque_date=>params[:cheque_date],:transaction_type=>params[:transaction_type],:add_contract_id=>params[:add_contract_id])
    redirect_to :back
  end
  
  def reports
    @search = PaymentHistory.search(params[:q])
    @payments=@search.result.order("collection_date DESC")
    @payment=0
      @search.result.each do |pay|
        @payment=@payment+ pay.amount
      end
  end

  def contract_expiry
    @contract=AddContract.where(:status=>"expired")
    @c=[]
    @expiry_date=params[:expiry_date]
    AddContract.all.each do |c|
      if request.method=='POST'
        @con= (Date.today..Date.today+params[:expiry_date].to_i).cover?(c.plans.last.renewal_date)
      else
        @con= (Date.today..Date.today+7).cover?(c.plans.last.renewal_date)
      end
      if @con==true
        @c<<c
      end
    end
  end
  
  def daily_report
    @user=User.all
    @leads=[]
    @no_of_leads=0
    @no_of_calls=0
    @sm=[]
    @search = LeadStatus.search(params[:q])  
    if params[:q].blank?
      @search.result.each do |lead|
        if lead.created_at.to_date==Date.today
          @leads<<lead
          @no_of_calls=@no_of_calls+1
          if lead.state=="Interested"
            @no_of_leads=@no_of_leads+1
          end
        end
      end
    else
      @search.result.each do |lead|
        @leads<<lead
        @no_of_calls=@no_of_calls+1
        if lead.state=="Interested"
          @no_of_leads=@no_of_leads+1
        end
      end
    end  
    respond_with(@leads) 
    ScheduleMeeting.all.each do |sm|
      if sm.created_at.to_date==Date.today
        @sm<<sm
      end
    end
  end

  def past_clients
    @past_clients=DailyUpdate.all
  end
  def not_called
    @category=Category.all
    @user=User.all
    @search = DailyUpdate.search(params[:q])
    @not_called= @search.result.where(:status=>'0').order('created_at DESC').page(params[:page]).per(25 )
    respond_with(@not_called)
  end
end

app/controllers/daily_updates_controller.rb
class DailyUpdatesController < ApplicationController
  before_action :set_daily_update, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html

  def index
    @user=User.all
    @category=Category.all
    @search = DailyUpdate.search(params[:q])
    if params[:q].nil?
      @daily_updates = @search.result.where(:status=>"0").order('created_at DESC').page(params[:page]).per(25)
    else
      @daily_updates = @search.result.order('created_at DESC').page(params[:page]).per(25)
    end
    respond_with(@daily_updates)
  end

  def show
    @lead_status = @daily_update.lead_status
    respond_with(@daily_update)
  end

  def schedule_meeting
    meeting_no= ScheduleMeeting.connection.execute("SELECT nextval('meeting_num_seq')")
    meeting='SE'+'0'+meeting_no[0]['nextval']
    @schedule=ScheduleMeeting.new(:meeting_no=>meeting,:meeting_date=>params[:meeting_date],:notes=>params[:notes],:assigned_to=>params[:assigned_to],:meeting_time=>params[:meeting_time],:venue=>params[:venue],:daily_update_id=>params[:daily_update_id])
    @schedule.save
    redirect_to :back
  end

  def meeting_logs
    @meetings = DailyUpdate.find(params[:client]).schedule_meeting.order('meeting_date Desc')
    render layout: false
  end

  def new
    @category=Category.all
    @daily_update = DailyUpdate.new
    @daily_update.lead_status.build 
    respond_with(@daily_update)
  end

  def edit
    @category=Category.all
    @lead_status = @daily_update.lead_status
  end

  def create
    @daily_update = DailyUpdate.new(daily_update_params)
    if @daily_update.save
      flash[:notice] = "Update successfully created"
      redirect_to new_daily_update_path
    else
      redirect_to '/daily_updates/new'
    end
  end

  def update  
    @daily_update.update(daily_update_params)
    if  params[:daily_update][:lead_status_attributes]["0"][:state].blank? or  params[:daily_update][:lead_status_attributes]["0"][:comment].blank?
    else
       @daily_update.update(:status=>1)
    end
    redirect_to edit_daily_update_path(@daily_update)
  end

  def destroy
    @daily_update.destroy
    respond_with(@daily_update)
  end

  def scheduled_call
    @search = LeadStatus.search(params[:q])
    @records = @search.result.order('schedule_next_call DESC')
    respond_with(@records)
  end
  
  def call_meeting
    if params[:commit]=='Save only status'
      @call=LeadStatus.create(:state=>params[:state],:user_id=>params[:user_id],:daily_update_id=>params[:daily_update_id1],:comment=>params[:comment],:schedule_next_call=>params[:schedule_next_call],:schedule_next_call_time=>params[:schedule_next_call_time])
      DailyUpdate.find(params[:daily_update_id1]).update(:status=>1)
    else
      @call=LeadStatus.create(:state=>params[:state],:user_id=>params[:user_id],:daily_update_id=>params[:daily_update_id1],:comment=>params[:comment],:schedule_next_call=>params[:schedule_next_call],:schedule_next_call_time=>params[:schedule_next_call_time])
      DailyUpdate.find(params[:daily_update_id1]).update(:status=>1)
      meeting_no= ScheduleMeeting.connection.execute("SELECT nextval('meeting_num_seq')")
      meeting='SE'+'0'+meeting_no[0]['nextval']
      @schedule=ScheduleMeeting.new(:meeting_no=>meeting,:meeting_date=>params[:meeting_date],:notes=>params[:notes],:assigned_to=>params[:assigned_to],:meeting_time=>params[:meeting_time],:venue=>params[:venue],:daily_update_id=>params[:daily_update_id1])
      @schedule.save
    end
    redirect_to :back
  end

  def call
    @call=LeadStatus.create(:state=>params[:state],:daily_update_id=>params[:daily_update_id1],:comment=>params[:comment],:schedule_next_call=>params[:schedule_next_call],:schedule_next_call_time=>params[:schedule_next_call_time])
    DailyUpdate.find(params[:daily_update_id1]).update(:status=>1)
    redirect_to :back
  end

  def fetch_daily
    @d=ScheduleMeeting.find(params[:daily_up]).daily_update_id
    render :json =>@d
  end

  def contract_updates
    if params[:description].present?
      @service=ServiceCall.create(:user_id=>params[:user_id],:description=>params[:description],:add_contract_id=>params[:add_contract_id])
    end
  end

  def messages
    @message=[]
    Messages.all.order('created_at DESC').each do |message|
      if message.sent_to==current_user.id and  !@message.include?(message.id) and !@message.include?(message.parent_message_id)
        @message<<message.parent_message_id
      end
    end
  end

  def view_more
    @msg=Messages.where(:parent_message_id=>params[:parent_message_id])
    @msg.each do |msg|
      if  msg.sent_to==current_user.id
        msg.update(:status=>1)
      end
    end
    @message=[]
    Messages.all.each do |message|
      if message.id.to_s==params[:parent_message_id] or message.parent_message_id.to_s==params[:parent_message_id]
        @message<<message
      end
    end
  end

  def new_message
    if params[:message].present?
      if params[:commit]=="Reply"
       @msg=Messages.find(params[:parent_message_id])
        if @msg.sent_to==current_user.id
          @message=Messages.create(:status=>0,:parent_message_id=>params[:parent_message_id],:user_id=>params[:user_id],:sent_to=>@msg.user_id,:message=>params[:message])
        else
          @message=Messages.create(:status=>0,:parent_message_id=>params[:parent_message_id],:user_id=>params[:user_id],:sent_to=>@msg.sent_to,:message=>params[:message])
        end
        redirect_to :back
      else
        @message=Messages.create(:status=>0,:user_id=>params[:user_id],:sent_to=>params[:send_to],:message=>params[:message])
        @message.update(:parent_message_id=>@message.id)
      end  
    end
  end
  
  def check_msg
    @message=ScheduleMeeting.where(:meeting_no=>params[:msg_id]).last
    @meeting_date=@message.meeting_date.strftime("%v")
    @meeting_time=@message.meeting_time.strftime("%I:%M%p")
    @venue=@message.venue
    @mom=@message.mom
    @assigned_to=User.find(@message.assigned_to).name
    @meeting_no=@message.meeting_no
    render :json =>{:meeting_no=>@meeting_no,:assigned_to=>@assigned_to,:mom=>@mom,:venue=>@venue,:meeting_date => @meeting_date, :meeting_time => @meeting_time }
  end
  def client_meetings
    @user=User.all
    @daily=DailyUpdate.all
    @meetings=[]
    @daily.each do |daily|
      if daily.lead_status.present?
        if daily.lead_status.last.state=='Client'
          if daily.schedule_meeting.present?
            @meetings<<daily.schedule_meeting.last.id
          end
        end
      end
    end
  end
  
  def todays_meetings
    @meetings=ScheduleMeeting.where(:meeting_date=>Date.today)
    @user=User.all
  end
private
  def set_daily_update
    @daily_update = DailyUpdate.find(params[:id])
  end
  def daily_update_params
    params.require(:daily_update).permit(:business,:status, :category_id,:contact_person,:user_id, :number, :designation, :status, :summary, :address, :email,lead_status_attributes: [:state,
                                                   :comment,:user_id,:schedule_next_call,:schedule_next_call_time])
  end
end

app/views/admin/daily_updates/_edit_meetings.html.erb
<button type="button" onclick="myFunctionupdate(this)" class="btn announce" data-toggle="modal" data-target="#edit_meeting_Modal" id="<%=id%>">
Edit
</button>
<div class="modal fade" id="edit_meeting_Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Lead Status</h4>
      </div>
      <div class="modal-body">
        <%= form_tag(update_meetings_path, :method=>'post', :multipart => true) do %>
          <table class="table">
            <tr>
               <td>
                 Date:
               </td>
               <td>
                 <%=date_field_tag :meeting_date %>
               </td>
             </tr>
             <tr>
               <td> Time:</td>
               <td><%= time_field_tag :meeting_time  %></td>
            </tr>
            <tr>
              <td>Venue:</td>
              <td><%=text_area_tag :venue %></td>
            </tr>
            <tr>
              <td>Notes:</td>
              <td><%=text_area_tag :notes%></td>
            </tr>
            <tr>
              <td>Assigned to :</td>
              <td><%=  select_tag "assigned_to", options_for_select(@user.collect{ |u| [ u.email,u.id]})%></td>
            </tr>
            <%= hidden_field_tag :s_id , params[:id]%>
            <tr>
            <td></td>
             <td> <%= submit_tag 'Submit' %></td>
            </tr>
          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/daily_updates/edit_meetings.html.erb
<section id="main-content">
  <section class="wrapper">
    <h3><i class="fa fa-angle-right"></i>Meetings</h3>
    <div class="row">
        <div class="col-md-12">
        </div>
      <div class="col-md-12 mt">
        <div class="content-panel">
        <div>
           <%= form_tag(update_meetings_path, :method=>'post', :multipart => true) do %>        
          <table class="table">
            <tr>
            <h3>Current Minutes of meeting</h3>
              <td>Mom:</td>
              <td><%=text_area_tag :mom %></td>
            </tr>
            <%= hidden_field_tag :ss_id,params[:id]%>         
            </br>
            <div class="toggl">
              <tr>
                <td>
                  <h3>Schedule next meeting</h3>
                </td>
              </tr>
            <tr>
              <td>Date:</td>
              <td><%= date_field_tag "meeting_date" %></td>
            </tr>
            <tr>
              <td> Time: </td>
              <td><%= time_field_tag "meeting_time" %></td>
            </tr>
            <tr>
              <td> Venue</td>
              <td><%= text_area_tag "venue", "", :size=>"20x5" %></td>
            </tr>
            <tr>
              <td> Notes</td>
              <td><%= text_area_tag "notes", "", :size=>"20x5" %></td>
            </tr>
            <tr>
              <td> Assigned to:</td>
              <td><%= select_tag "assigned_to", options_from_collection_for_select(User.all, "id", "email"),:class=>"form-control",:style=>"width:30%"%></td>
            </tr>
            <%@a=ScheduleMeeting.find(params[:id]).daily_update_id%>
            <%= hidden_field_tag :daily_update_id ,@a%>
            <tr>
              <td></td>
              <td class="a"><%= submit_tag 'Save Only Mom',:class=>"btn btn-primary",:id=>"mom" %> <%= submit_tag 'Save both' ,:class=>"btn btn-primary ",:id=>"both"%></td>
            </tr>
          </table>
        <% end %> 
          </br>         
          <%= link_to "Back",meetings_path%> 
          </div>
        </div>
      </div>
    </div>
  </section>   
</section> 
<script>
  $( document ).ready(function() {
   $( ".toggl" ).hide();
  });
  $( ".togg" ).click(function() {
    $( ".toggl" ).show();
  });
</script>

app/views/admin/daily_updates/index_contract.html.erb
<section id="main-content">
  <section class="wrapper">
    <h3><i class="fa fa-angle-right"></i>Listing Contracts</h3>
    <div class="row">
      <div class="col-md-12">
      </div>
      <div class="col-md-12 mt">
        <div class="content-panel" style="width:1000px">
        <%= search_form_for @search, :html=>{:class=>"form-inline", :role=>"form" , mothod: 'post'} do |f| %>
          <%if params[:q].present?%>
            <%= f.label :client_name ,:class=>"f-label" %>
            <%= f.text_field :daily_update_contact_person_cont ,:class=>'form-control',:value=>params[:q][:daily_update_contact_person_cont]%>
            <%= f.label :domain_name ,:class=>"f-label"%>
            <%= f.text_field :domain_name_cont ,:class=>'form-control',:value=>params[:q][:domain_name_cont]%>
            <%= f.label :plan, "Plan" ,:class=>"f-label"%>
            <%= f.select :plans_plan_type_eq ,(AddContract::PLANS), {:include_blank=>"select"},:class=>'form-control',:value=>params[:q][:plans_plan_type_eq]%>
            <%= f.label :status, "Status" ,:class=>"f-label"%>
            <%= f.select :status_eq ,(AddContract::STATUS), {:include_blank=>"select"},:class=>'form-control',:value=>params[:q][:status_eq]%></br>
            </br>
            <%= f.label :priority, "Priority" ,:class=>"f-label"%>
            <%= f.select :priority_eq ,(AddContract::PRIORITY), {:include_blank=>"select"},:class=>'form-control',:value=>params[:q][:status_eq]%>            
            <%= f.label :work_status, "Work status",:class=>"f-label" %>
            <%= f.select :work_status_eq ,(AddContract::WORKSTATUS), {:include_blank=>"select"},:class=>'form-control',:value=>params[:q][:work_status_eq]%>
            <%= f.label :renewal_date_gteq, "Filter By Date" ,:class=>"f-label"%>
            <%= f.date_field :plans_renewal_date_gteq ,:class=>'form-control',:value=>params[:q][:plans_renewal_date_gteq]%>
            <%= f.label :renewal_date_lteq, "and" %>
            <%= f.date_field :plans_renewal_date_lteq,:class=>'form-control' ,:value=>params[:q][:plans_renewal_date_lteq]%>
          <%else%>
            <%= f.label :client_name ,:class=>"f-label" %>
            <%= f.text_field :daily_update_contact_person_cont ,:class=>'form-control'%>
            <%= f.label :domain_name ,:class=>"f-label"%>
            <%= f.text_field :domain_name_cont ,:class=>'form-control'%>
            <%= f.label :plan, "Plan" ,:class=>"f-label"%>
            <%= f.select :plans_plan_type_eq ,(AddContract::PLANS), {:include_blank=>"select"},:class=>'form-control'%>
            <%= f.label :status, "Status" ,:class=>"f-label"%>
            <%= f.select :status_eq ,(AddContract::STATUS), {:include_blank=>"select"},:class=>'form-control'%></br>
            </br>
            <%= f.label :priority, "Priority" ,:class=>"f-label"%>
            <%= f.select :priority_eq ,(AddContract::PRIORITY), {:include_blank=>"select"},:class=>'form-control'%>
            <%= f.label :work_status, "Work status",:class=>"f-label" %>
            <%= f.select :work_status_eq ,(AddContract::WORKSTATUS), {:include_blank=>"select"},:class=>'form-control'%>
            <%= f.label :renewal_date_gteq, "Filter By Date" ,:class=>"f-label"%>
            <%= f.date_field :plans_renewal_date_gteq ,:class=>'form-control'%>
            <%= f.label :renewal_date_lteq, "and" %>
            <%= f.date_field :plans_renewal_date_lteq,:class=>'form-control' %>
          <%end%>
          <div class="actions" align="center"><%= f.submit "Search" %></div>
        <% end %>
          <div style="float:right;"><%= link_to 'New Contract', new_contract_path , :class=>"btn btn-primary",:style=>"margin-right:10px"%></div>
            <h4>There are total <%=@contracts.count%> contracts</h4>
          <table class='table'>
            <thead>
              <tr>
                <th>S. no</th>
                <th>Client</th>
                <th>Domain name</th>
                <th>Start Date</th>
                <th><%= sort_link(@search, :plans_renewal_date, "Renewal Date") %></th>
                <th class="days"><%= sort_link(@search, :created_at, "Days") %></th>                
                <th>Status</th>
                <th> Work Status</th>
                <th> Priority</th>
                <th colspan="3">Actions</th>
              </tr>
            </thead>          
            <tbody>
            <%s_no=0%>
              <% @contracts.each do |contract| %>
                <tr>
                  <td><%=s_no=s_no+1%></td>
                  <td><%= DailyUpdate.client(contract.daily_update_id).contact_person %></td>
                  <td><%= contract.domain_name %></td>
                   <td><%= format_date(contract.created_at) %></td>
                  <td style="width:100px"><%= format_date(contract.plans.last.renewal_date.to_date) if contract.plans.last.renewal_date.present? if contract.plans.present?%></td>

                  <td><%=(Date.today-contract.created_at.to_date).to_i%></td>
                  
                  <td><%= contract.plans.last.plan_type if contract.plans.present?%></td>
                  <td><%= contract.status %>
                    <%if contract.status=="expired"%>
                      <%= button_to "Notify", notify_expiry_path(:id=>contract.daily_update_id,:contract_id=>contract.id)%>
                    <%end%>
                  </td>       
                  <%=hidden_field_tag :a,0%>           
                   <td><%= contract.work_status %></td>
                   <td><%= contract.priority %></td>
                   <td><%= link_to 'Updates' ,contract_updates_path(:id=>contract.id)%></br><%= link_to 'Payment history' ,payment_history_path(:id=>contract.id)%></br><%=render  :partial=> "edit_contract", locals: {:id => contract.id}%>
                 </td>
                </tr>
              <% end %>
            </tbody>
          </table>              
        </div>
      </div>
    </div>
  </section>   
</section>