config/routes.rb
Rails.application.routes.draw do
  resources :daily_updates
  devise_for :users , controllers: { sessions: "sessions" }
  root 'daily_updates#index'
  namespace :admin do
    resources :manage_user
    resources :users
    resources :categories
    get 'deactivate' => 'manage_user#deactivate', :as=>'deactivate'
    get 'daily_updates/index'
  end
    get 'past_clients'=>"admin/daily_updates#past_clients"
    get 'check_msg'=>"daily_updates#check_msg"
    get 'add_contracts'=>'admin/daily_updates#index_contract'
    get 'new_contract' => 'admin/daily_updates#new_contract'
    get 'scheduled_call' => 'daily_updates#scheduled_call'
    post 'create_contract' => 'admin/daily_updates#create_contract'
    get 'fetch_plans' => 'admin/daily_updates#fetch_plans'
    get 'fetch_meetings' => 'admin/daily_updates#fetch_meetings'
    get 'fetch_logs' => 'admin/daily_updates#logs'
    get 'fetch_contract' => 'admin/daily_updates#fetch_contract'
    get 'fetch_daily' => 'daily_updates#fetch_daily'
    get 'index_contract' => 'admin/daily_updates#index_contract'
    get 'edit_contract' => 'admin/daily_updates#edit_contract'
    post 'update_contract' => 'admin/daily_updates#update_contract'
    post 'call' => 'daily_updates#call'
    post 'call_meeting' => 'daily_updates#call_meeting'
    get 'show_meetings' => 'admin/daily_updates#show_meetings'
    get 'lead_statuses' => 'daily_updates#scheduled_call'
    get 'meeting_logs' => 'daily_updates#meeting_logs'
    get 'not_called'=>'admin/daily_updates#not_called'
    get 'contract_updates'=>'daily_updates#contract_updates'
    get 'messages'=>'daily_updates#messages'
    get 'view_more'=>'daily_updates#view_more'
    get 'new_message'=>'daily_updates#new_message'
    post 'new_message'=>'daily_updates#new_message'
    post 'contract_updates'=>'daily_updates#contract_updates'
    get 'client_meetings'=>'daily_updates#client_meetings'
    get 'todays_meetings'=>'daily_updates#todays_meetings'
  as :admin do
    post 'notify_expiry'=>'admin/daily_updates#notify_expiry'
    post 'lead_statuses'=>'admin/daily_updates#daily_report'
    get 'daily_report'=>'admin/daily_updates#daily_report'
    post 'admin/new_users' => 'admin/users#create'
    post 'user_daily_updates' => 'admin/daily_updates#user_daily_updates'
    post 'schedule_meeting'=>'daily_updates#schedule_meeting'
    post 'schedule_meetings'=>'admin/daily_updates#meetings'
    get 'schedule_meetings'=>'admin/daily_updates#meetings'
    get 'payment_histories'=>'admin/daily_updates#reports'
    post 'reports'=>'admin/daily_updates#reports'
    get 'user_daily_updates' => 'admin/daily_updates#user_daily_updates'
    get 'meetings'=>'admin/daily_updates#meetings'
    get 'edit_meetings'=>'admin/daily_updates#edit_meetings'
    post 'update_meetings'=>'admin/daily_updates#update_meetings'
    get 'client_management' => 'admin/daily_updates#client_management'
    get 'payment_history' => 'admin/daily_updates#payment_history'
    get 'contract_expiry' => 'admin/daily_updates#contract_expiry'
    post 'contract_expiry' => 'admin/daily_updates#contract_expiry'
    post 'create_payment' => 'admin/daily_updates#create_payment'    
  end
end

app/controllers/admin/manage_user_controller.rb
class Admin::ManageUserController < ApplicationController
	before_filter :check_user

  def check_user
    redirect_to daily_updates_path if !current_user.admin?
  end

	def index
		@user = User.all.where(:admin => nil)
	end

  def deactivate
 	  @user = User.find(params[:id])
 	  if @user.active
 	    @user.active = false
 	    @user.save
 	    respond_to do |format|
 	     	format.json {render json: "user deactivated"}
 	    end
 	  else
 	  	@user.active = true
 	  	@user.save
 	  	respond_to do |format|
 	     	format.json  {render json: "user activated"}
 	    end
 	  end
  end

	def new
		@user = User.new
	end

	def edit
		@user = User.find(params[:id])
	end	
end

app/views/admin/manage_user/edit.html.erb
<section id="main-content">
  <section class="wrapper">
    <h3><i class="fa fa-angle-right"></i>Edit New User</h3>
    <div class="row">
      <div class="col-md-12">
      </div>
      <div class="col-md-12 mt">
        <div class="content-panel" >
          <%= form_for(@user, url: admin_user_path , method: 'put') do |f| %>
            <div><%= f.label :name ,:class=>"f-label"%><br />
            <%= f.text_field :name,:class=>"form-control" ,:style=> 'width:30%; margin-left:10px;' %></div>
            <div><%= f.label :email,:class=>"f-label" %><br/>
            <%= f.email_field :email, autofocus: true ,:class=>"form-control" ,:style=> 'width:30%; margin-left:10px;'%></div>
            <div><%= f.label :role,:class=>"f-label" %><br/>
            <%= f.select :role, User::ROLES, {:include_blank=>"select"}, :class=>"form-control" ,:style=> 'width:30%; margin-left:10px;'%></div><br>
            <div><%= f.submit "Update", :class=>"btn btn-primary",:style=>"margin-left:10px;"  %></div>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  </section>   
</section>

app/views/admin/manage_user/index.html.erb
<section id="main-content">
  <section class="wrapper">
    <h3><i class="fa fa-angle-right"></i>This Client Status Till Now</h3>
    <div class="row">
      <div class="col-md-12">
      </div>
      <div class="col-md-12 mt">
        <div class="content-panel">
          <div style="float:right;color:#fff;"><%= link_to 'Create new User' , new_admin_manage_user_path , :class=>"btn btn-primary",:style=>"margin-right:10px"%></div>          
          <table class='table'>
            <thead>
          	<tr><th>S. no</th><th>Email</th><th> Role </th><th>Change permission</th></tr></thead>
            <%users=0%>
          <% @user.each do |ls|%>
          
          	<tr>
            <td><%=users=users+1%>.</td>
          	<td><%= link_to ls.email,user_daily_updates_path(:id=>ls.id) %></td>
          	<td></td>
          	<td><%= check_box_tag 'Deactivate', 'Deactivate', !ls.active , :class=> 'deactivate' , :val => ls.id%><% if !ls.active %> Activate Account <%else%> Deactivate Account<%end%></td><td><%= link_to "Update user" , edit_admin_manage_user_path(ls)%></td></tr>
          <%end%>
          </table>
        </div>
      </div>
    </div>
  </section>   
</section>

<script>
  $('.deactivate').on('change', function() {
    $.ajax('/admin/deactivate', {
        type: 'get',
        dataType: 'html',
        data: {id: $(this).attr('val') },
        success: function(data, textStatus, jqXHR) {
        alert(data);
        location.reload();
        }
      });
  });
</script>

app/views/admin/manage_user/new.html.erb
<section id="main-content">
  <section class="wrapper">
    <h3><i class="fa fa-angle-right"></i>Create New User</h3>
    <div class="row">
      <div class="col-md-12">
      </div>
      <div class="col-md-12 mt">
        <div class="content-panel" >
          <%= form_for(@user, url: admin_users_path , method: 'post') do |f| %>
            <div><%= f.label :name,:class=>"f-label" %><br />
            <%= f.text_field :name , :class=>"form-control" ,:style=> 'width:30%; margin-left:10px;'%></div>
            <div>
              <%= f.label :email ,:class=>"f-label"%><br/>
              <%= f.email_field :email, autofocus: true ,:class=>"form-control" ,:style=> 'width:30%; margin-left:10px;'%>
            </div>          
            <div>
              <%= f.label :password ,:class=>"f-label"%>
                <% if @validatable %>
                  <i>(<%= @minimum_password_length %> characters minimum)</i>
                <% end %>
                <br />
              <%= f.password_field :password, autocomplete: "off",:class=>"form-control" ,:style=> 'width:30%; margin-left:10px;' %></div>          
            <div>
              <%= f.label :password_confirmation ,:class=>"f-label"%><br />
              <%= f.password_field :password_confirmation, autocomplete: "off",:class=>"form-control" ,:style=> 'width:30%; margin-left:10px;' %></div>
              <%= f.label :role ,:class=>"f-label"%><br />
              <%= f.select :role, User::ROLES, {:include_blank=>"select"}, :class=>"form-control" ,:style=> 'width:30%; margin-left:10px;'%> <br>
            <div><%= f.submit "Create", :class=>"btn btn-primary",:style=>"margin-left:10px;" %></div>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>   
</section>