config/routes.rb
Rails.application.routes.draw do
  resources :daily_updates
  devise_for :users , controllers: { sessions: "sessions" }
  root 'daily_updates#index'
  namespace :admin do
    resources :manage_user
    resources :users
    resources :categories
    get 'deactivate' => 'manage_user#deactivate', :as=>'deactivate'
    get 'daily_updates/index'
  end
    get 'past_clients'=>"admin/daily_updates#past_clients"
    get 'check_msg'=>"daily_updates#check_msg"
    get 'add_contracts'=>'admin/daily_updates#index_contract'
    get 'new_contract' => 'admin/daily_updates#new_contract'
    get 'scheduled_call' => 'daily_updates#scheduled_call'
    post 'create_contract' => 'admin/daily_updates#create_contract'
    get 'fetch_plans' => 'admin/daily_updates#fetch_plans'
    get 'fetch_meetings' => 'admin/daily_updates#fetch_meetings'
    get 'fetch_logs' => 'admin/daily_updates#logs'
    get 'fetch_contract' => 'admin/daily_updates#fetch_contract'
    get 'fetch_daily' => 'daily_updates#fetch_daily'
    get 'index_contract' => 'admin/daily_updates#index_contract'
    get 'edit_contract' => 'admin/daily_updates#edit_contract'
    post 'update_contract' => 'admin/daily_updates#update_contract'
    post 'call' => 'daily_updates#call'
    post 'call_meeting' => 'daily_updates#call_meeting'
    get 'show_meetings' => 'admin/daily_updates#show_meetings'
    get 'lead_statuses' => 'daily_updates#scheduled_call'
    get 'meeting_logs' => 'daily_updates#meeting_logs'
    get 'not_called'=>'admin/daily_updates#not_called'
    get 'contract_updates'=>'daily_updates#contract_updates'
    get 'messages'=>'daily_updates#messages'
    get 'view_more'=>'daily_updates#view_more'
    get 'new_message'=>'daily_updates#new_message'
    post 'new_message'=>'daily_updates#new_message'
    post 'contract_updates'=>'daily_updates#contract_updates'
    get 'client_meetings'=>'daily_updates#client_meetings'
    get 'todays_meetings'=>'daily_updates#todays_meetings'
  as :admin do
    post 'notify_expiry'=>'admin/daily_updates#notify_expiry'
    post 'lead_statuses'=>'admin/daily_updates#daily_report'
    get 'daily_report'=>'admin/daily_updates#daily_report'
    post 'admin/new_users' => 'admin/users#create'
    post 'user_daily_updates' => 'admin/daily_updates#user_daily_updates'
    post 'schedule_meeting'=>'daily_updates#schedule_meeting'
    post 'schedule_meetings'=>'admin/daily_updates#meetings'
    get 'schedule_meetings'=>'admin/daily_updates#meetings'
    get 'payment_histories'=>'admin/daily_updates#reports'
    post 'reports'=>'admin/daily_updates#reports'
    get 'user_daily_updates' => 'admin/daily_updates#user_daily_updates'
    get 'meetings'=>'admin/daily_updates#meetings'
    get 'edit_meetings'=>'admin/daily_updates#edit_meetings'
    post 'update_meetings'=>'admin/daily_updates#update_meetings'
    get 'client_management' => 'admin/daily_updates#client_management'
    get 'payment_history' => 'admin/daily_updates#payment_history'
    get 'contract_expiry' => 'admin/daily_updates#contract_expiry'
    post 'contract_expiry' => 'admin/daily_updates#contract_expiry'
    post 'create_payment' => 'admin/daily_updates#create_payment'    
  end
end

app/views/layouts/_footer.html.erb
<footer class="site-footer">
  <div class="text-center">
    Lead management system-2014
    <a class="go-top">
      <i class="fa fa-angle-up"></i>
    </a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<html lang="en">
  <section id="container" >
    <header class="header black-bg">
      <div class="sidebar-toggle-box">
        <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation">
        </div>
      </div>
      <a class="logo" href="daily_updates/index">Lead Management System
      </a>
      <div class="top-menu">
        <ul class="nav pull-right top-menu">
          <% if user_signed_in? %>
            <li style="margin-top:20px"> Signed in as <%= current_user.email %>. Not you? </li>
            <li><%= link_to "Sign out", destroy_user_session_path,:method => :delete  ,:class=>"logout"%></>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path ,:class=>"logout" %></li>
          <% end %>
          </ul>
      </div>
    </header>
  </section>  
</html> 



         

app/views/layouts/_sidebar.html.erb
<% if current_user.admin==true%>
<aside>
  <div id="sidebar"  class="nav-collapse ">
    <ul class="sidebar-menu" id="nav-accordion">
      
     <h5 class="centered"></h5>
     <li class="mt">
        <i class="fa fa-dashboard"></i>
        <%@m=Messages.where(:status=>"0",:sent_to=>current_user.id)%>
        <span><%= link_to "Messages" , messages_path %><%=@m.count if @m.present?%> <%if @m.present?%>unread messages<%end%></span>
      </li>
     
      <li class="sub-menu">
        <i class="fa fa-dashboard"></i>
        <span><%= link_to "Meetings" , meetings_path %></span>
      </li>
        <li class="sub-menu">
        <i class="fa fa-dashboard"></i>
        <span><%= link_to "Todays Meetings" , todays_meetings_path %></span>
      </li>
      <li class="sub-menu">
        <i class="fa fa-book"></i>
        <span><%= link_to "User Management" , admin_manage_user_index_path%></span>
        <ul class="sub">
          <li><a  href="login.html">Login</a></li>
        </ul>
      </li>
      <li class="sub-menu">
        <i class="fa fa-th"></i>
        <span><%= link_to "Lead Management" , admin_daily_updates_index_path%></span>
      </li>
      <li class="sub-menu">
        <i class="fa fa-th"></i>
        <span><%= link_to "Client Management" , client_management_path%></span>
      </li>
      <li class="sub-menu">
        <i class="fa fa-th"></i>
        <span><%= link_to "Account Management" , index_contract_path%></span>
      </li>
      <li class="sub-menu">
        <i class="fa fa-th"></i>
        <span><%= link_to "Categories" , admin_categories_path%></span>
      </li>
       <li class="sub-menu">
        <span><%= link_to "Scheduled calls" ,scheduled_call_path%></span>
      </li> 
      <li class="sub-menu">
        <span><%= link_to "Payment Reports" ,payment_histories_path%></span>
      </li>
      <li class="sub-menu">
        <span><%= link_to "Contract expiry Reports" ,contract_expiry_path%></span>
      </li>  
      <li class="sub-menu">
        <span><%= link_to "Daily Report" ,daily_report_path%></span>
      </li>       
    </ul>
  </div>
</aside>
<%elsif current_user.role=="Manager"%>
<aside>
  <div id="sidebar"  class="nav-collapse ">
    <ul class="sidebar-menu" id="nav-accordion">
      
     <h5 class="centered"></h5>
     <li class="sub-menu">
        <i class="fa fa-dashboard"></i>
         <%@m=Messages.where(:status=>"0",:sent_to=>current_user.id)%>
        <span><%= link_to "Messages" , messages_path %><%=@m.count if @m.present?%> <%if @m.present?%>unread messages<%end%></span>
      </li>
      <li class="sub-menu">
        <i class="fa fa-dashboard"></i>
        <span><%= link_to "New records" , new_daily_update_path %></span>
      </li>
      <li class="sub-menu">
        <i class="fa fa-book"></i>
        <span><%= link_to "View records" , daily_updates_path %></span>
      </li>
       <li class="sub-menu">
        <i class="fa fa-dashboard"></i>
        <span><%= link_to "Todays Meetings" , todays_meetings_path %></span>
      </li>
      <li class="sub-menu">
        <span><%= link_to "Meetings" , meetings_path %></span>
      </li>
       <li class="sub-menu">
        <i class="fa fa-th"></i>
        <span><%= link_to "Client Management" , client_management_path%></span>
      </li>
      <li class="sub-menu">
        <i class="fa fa-th"></i>
        <span><%= link_to "Account Management" , index_contract_path%></span>
      </li>
       <li class="sub-menu">
        <span><%= link_to "Scheduled calls" ,scheduled_call_path%></span>
      </li>
       <li class="sub-menu">
        <span><%= link_to "Client Meetings" ,client_meetings_path%></span>
      </li>
    </ul>
  </div>
</aside>
<%else%>
<aside>
  <div id="sidebar"  class="nav-collapse ">
    <ul class="sidebar-menu" id="nav-accordion">
    <h5 class="centered"></h5>
     <li class="sub-menu">
        <i class="fa fa-dashboard"></i>
         <%@m=Messages.where(:status=>"0",:sent_to=>current_user.id)%>
        <span><%= link_to "Messages" , messages_path %><%=@m.count if @m.present?%> <%if @m.present?%>unread messages<%end%></span>
      </li>
      <li class="sub-menu">
        <i class="fa fa-dashboard"></i>
        <span><%= link_to "New records" , new_daily_update_path %></span>
      </li>
      <li class="sub-menu">
        <i class="fa fa-book"></i>
        <span><%= link_to "View records" , daily_updates_path %></span>
      </li>
        <li class="sub-menu">
        <i class="fa fa-dashboard"></i>
        <span><%= link_to "Todays Meetings" , todays_meetings_path %></span>
      </li>
      <li class="sub-menu">
        <span><%= link_to "Meetings" , meetings_path %></span>
      </li>
      <li class="sub-menu">
        <span><%= link_to "Scheduled calls" ,scheduled_call_path%></span>
      </li>
    </ul>
  </div>
</aside>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Lead Management System</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %> 
  </head>
  <body>
    <%if current_user.present?%>
      <%= render 'layouts/header'%>
      <%= render 'layouts/sidebar'%>
    <%end%>    
    <form class="navbar-form navbar-right" role="form">
      <% if user_signed_in? %>    
        <% if current_user.admin? %>
          <%= link_to "Meetings" , meetings_path,:style=>"color:#ffffff;text-decoration:none;" %>
          <%= link_to "| User Management" , admin_manage_user_index_path,  :style=>"color:#ffffff;text-decoration:none;" %> 
          <%= link_to "| Lead Management" , admin_daily_updates_index_path,:style=>"color:#ffffff;text-decoration:none;" %>
        <%else%>
        <%end%>
        Signed in as <%= current_user.email %>. Not you?
        <div class="form-group">  
          <%= link_to "Sign out", destroy_user_session_path,:method => :delete ,:class=>"btn btn-success"%>
        </div>
      <% else %> 
        <%= link_to "Sign in", new_user_session_path %>
      <% end %>
    </form>
    <div class="container" >
      <div class="row">
        <%if notice.present?%>
          <div class="notice" style="margin-top:50px;"><%= notice %></div>
          <%end%>
          <% if alert.present?%>
          <div class="alert" style="margin-top:50px;"><%= alert %></div>
          <%end%>
          <%= yield %>
      </div>
      <hr>
      <%if current_user.present?%>
        <%=render 'layouts/footer'%>
      <%end%>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
   </body>
</html>